language: r
cache: packages
pandoc_version: 1.19.2.4

script:
  - Rscript -e 'bookdown::render_book("index.rmd", "bookdown::gitbook")'
  - Rscript -e 'bookdown::render_book("index.rmd", "bookdown::pdf_book")'

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local-dir: docs
  on:
    branch: master
